/*
 * Copyright 2020 EPAM Systems, Inc. (https://www.epam.com/)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

const checkoutMocked = {
  action: "Checkout-Begin",
  queryString: "stage=shipping",
  locale: "en_US",
  tracking_consent: null,
  csrf: {
    tokenName: "csrf_token",
    token:
      "w0TWPtE0H05DH9JsO1uYZm18y84fVl_fXZkaYUWbOMoBxKVsI9EzJoWTNuw7qXNu_2skaCaMPeJ6tA7ffTIAtJ5OzefZp_Wa8N9L_mQHTWTlzNOBqKTWkwAGKR76YsXbVpNieasIWFlccsvJ3ewqs0DdSRiIgP_26Ymi3-jkz1j3P8ODMq8=",
  },
  order: {
    resources: {
      noSelectedPaymentMethod: "error.no.selected.payment.method",
      cardType: "Credit",
      cardEnding: "Ending",
      shippingMethod: "Shipping Method",
      items: "included items",
      item: "included item",
      addNewAddress: "New Address",
      newAddress: "New Address",
      shipToAddress: "msg.ship.to.address",
      shippingAddresses: "- Existing Shipments -",
      accountAddresses: "- Address Book -",
      shippingTo: "msg.shipping.to",
      shippingAddress: "Shipping Address:",
      addressIncomplete: "Please edit shipping address information and save.",
      giftMessage: "Gift Message:",
    },
    shippable: false,
    usingMultiShipping: false,
    orderNumber: null,
    priceTotal: "$132.27",
    creationDate: "2020-05-19T15:54:28.511Z",
    orderEmail: null,
    orderStatus: null,
    productQuantityTotal: 2,
    totals: {
      subTotal: "$117.98",
      totalShippingCost: "$7.99",
      grandTotal: "$132.27",
      totalTax: "$6.30",
      orderLevelDiscountTotal: {
        value: 0,
        formatted: "$0.00",
      },
      shippingLevelDiscountTotal: {
        value: 0,
        formatted: "$0.00",
      },
      discounts: [],
      discountsHtml: "\r\n",
    },
    steps: {
      shipping: {
        iscompleted: false,
      },
      billing: {
        iscompleted: false,
      },
    },
    items: {
      items: [
        {
          uuid: "0451566ef4aa3a2997028dea25",
          id: "701642887584M",
          productName: "Belted Boat Neck",
          productType: "variant",
          brand: null,
          price: {
            sales: {
              value: 58.99,
              currency: "USD",
              formatted: "$58.99",
              decimalPrice: "58.99",
            },
            list: {
              value: 79,
              currency: "USD",
              formatted: "$79.00",
              decimalPrice: "79.00",
            },
          },
          images: {
            small: [
              {
                alt: "Belted Boat Neck, Laurel, small",
                url:
                  "/on/demandware.static/-/Sites-apparel-m-catalog/default/dwa3fbe726/images/small/PG.10214675.JJ0NLB1.PZ.jpg",
                title: "Belted Boat Neck, Laurel",
                index: "0",
                absURL:
                  "https://zzrp-005.sandbox.us01.dx.commercecloud.salesforce.com/on/demandware.static/-/Sites-apparel-m-catalog/default/dwa3fbe726/images/small/PG.10214675.JJ0NLB1.PZ.jpg",
              },
            ],
          },
          variationAttributes: [
            {
              displayName: "Color",
              displayValue: "Laurel",
              attributeId: "color",
              id: "color",
            },
            {
              displayName: "Size",
              displayValue: "S",
              attributeId: "size",
              id: "size",
            },
          ],
          availability: {
            messages: ["In Stock"],
            inStockDate: null,
          },
          available: true,
          quantity: 2,
          isGift: false,
          renderedPromotions: "",
          UUID: "7326a9ae3d6a8388a31f69adea",
          isOrderable: true,
          shipmentUUID: "c535af73486ded4d3c9681e6d5",
          isBonusProductLineItem: false,
          priceTotal: {
            price: "$117.98",
            renderedPrice:
              '\r\n\r\n\r\n<div class="strike-through\r\nnon-adjusted-price"\r\n>\r\n    null\r\n</div>\r\n<div class="pricing line-item-total-price-amount item-total-null">$117.98</div>\r\n\r\n',
          },
          quantityOptions: {
            minOrderQuantity: 1,
            maxOrderQuantity: 10,
          },
          options: [],
          bonusProductLineItemUUID: null,
          preOrderUUID: null,
          discountLineItems: [],
          bonusProducts: null,
        },
      ],
      totalQuantity: 2,
    },
    billing: {
      billingAddress: {
        address: null,
      },
      payment: {
        applicablePaymentMethods: [
          {
            ID: "CREDIT_CARD",
            name: "Credit Card",
          },
        ],
        applicablePaymentCards: [
          {
            cardType: "Visa",
            name: "Visa",
          },
          {
            cardType: "Amex",
            name: "American Express",
          },
          {
            cardType: "Master Card",
            name: "MasterCard",
          },
          {
            cardType: "Discover",
            name: "Discover",
          },
        ],
        selectedPaymentInstruments: [],
      },
      matchingAddressId: false,
    },
    shipping: [
      {
        UUID: "c535af73486ded4d3c9681e6d5",
        productLineItems: {
          items: [
            {
              uuid: "0451566ef4aa3a2997028dea25",
              id: "701642887584M",
              productName: "Belted Boat Neck",
              productType: "variant",
              brand: null,
              price: {
                sales: {
                  value: 58.99,
                  currency: "USD",
                  formatted: "$58.99",
                  decimalPrice: "58.99",
                },
                list: {
                  value: 79,
                  currency: "USD",
                  formatted: "$79.00",
                  decimalPrice: "79.00",
                },
              },
              images: {
                small: [
                  {
                    alt: "Belted Boat Neck, Laurel, small",
                    url:
                      "/on/demandware.static/-/Sites-apparel-m-catalog/default/dwa3fbe726/images/small/PG.10214675.JJ0NLB1.PZ.jpg",
                    title: "Belted Boat Neck, Laurel",
                    index: "0",
                    absURL:
                      "https://zzrp-005.sandbox.us01.dx.commercecloud.salesforce.com/on/demandware.static/-/Sites-apparel-m-catalog/default/dwa3fbe726/images/small/PG.10214675.JJ0NLB1.PZ.jpg",
                  },
                ],
              },
              variationAttributes: [
                {
                  displayName: "Color",
                  displayValue: "Laurel",
                  attributeId: "color",
                  id: "color",
                },
                {
                  displayName: "Size",
                  displayValue: "S",
                  attributeId: "size",
                  id: "size",
                },
              ],
              availability: {
                messages: ["In Stock"],
                inStockDate: null,
              },
              available: true,
              quantity: 2,
              isGift: false,
              renderedPromotions: "",
              UUID: "7326a9ae3d6a8388a31f69adea",
              isOrderable: true,
              shipmentUUID: "c535af73486ded4d3c9681e6d5",
              isBonusProductLineItem: false,
              priceTotal: {
                price: "$117.98",
                renderedPrice:
                  '\r\n\r\n\r\n<div class="strike-through\r\nnon-adjusted-price"\r\n>\r\n    null\r\n</div>\r\n<div class="pricing line-item-total-price-amount item-total-null">$117.98</div>\r\n\r\n',
              },
              quantityOptions: {
                minOrderQuantity: 1,
                maxOrderQuantity: 10,
              },
              options: [],
              bonusProductLineItemUUID: null,
              preOrderUUID: null,
              discountLineItems: [],
              bonusProducts: null,
            },
          ],
          totalQuantity: 2,
        },
        applicableShippingMethods: [
          {
            ID: "001",
            displayName: "Ground",
            description: "Order received within 7-10 business days",
            estimatedArrivalTime: "7-10 Business Days",
            default: true,
            shippingCost: "$7.99",
            selected: true,
          },
          {
            ID: "002",
            displayName: "2-Day Express",
            description: "Order received in 2 business days",
            estimatedArrivalTime: "2 Business Days",
            default: false,
            shippingCost: "$11.99",
            selected: false,
          },
          {
            ID: "003",
            displayName: "Overnight",
            description: "Order received the next business day",
            estimatedArrivalTime: "Next Day",
            default: false,
            shippingCost: "$19.99",
            selected: false,
          },
          {
            ID: "012",
            displayName: "Express",
            description:
              "Orders shipped outside continental US received in 2-3 business days",
            estimatedArrivalTime: "2-3 Business Days",
            default: false,
            shippingCost: "$22.99",
            selected: false,
          },
          {
            ID: "021",
            displayName: "USPS",
            description:
              "Order shipped by USPS received within 7-10 business days",
            estimatedArrivalTime: "7-10 Business Days",
            default: false,
            shippingCost: "$7.99",
            selected: false,
          },
        ],
        selectedShippingMethod: {
          ID: "001",
          displayName: "Ground",
          description: "Order received within 7-10 business days",
          estimatedArrivalTime: "7-10 Business Days",
          default: true,
          shippingCost: "$7.99",
          selected: true,
        },
        matchingAddressId: false,
        shippingAddress: null,
        isGift: false,
        giftMessage: null,
      },
    ],
  },
  customer: {
    profile: null,
    addresses: [],
    preferredAddress: null,
    payment: null,
    registeredUser: false,
    isExternallyAuthenticated: false,
    customerPaymentInstruments: null,
  },
  forms: {
    shippingForm: {
      valid: true,
      htmlName: "dwfrm_shipping",
      dynamicHtmlName: "dwfrm_shipping_d0qcdxfkkiqf",
      error: "address.invalid",
      attributes: 'name = "dwfrm_shipping" id = "dwfrm_shipping"',
      formType: "formGroup",
      shipmentUUID: {
        htmlValue: "",
        mandatory: "",
        dynamicHtmlName: "dwfrm_shipping_shipmentUUID_d0aofkfbwzyl",
        htmlName: "dwfrm_shipping_shipmentUUID",
        valid: true,
        maxLength: 2147483647,
        minLength: 0,
        regEx: null,
        formType: "formField",
      },
      productLineItemUUID: {
        htmlValue: "",
        mandatory: "",
        dynamicHtmlName: "dwfrm_shipping_productLineItemUUID_d0wluxwfyrij",
        htmlName: "dwfrm_shipping_productLineItemUUID",
        valid: true,
        maxLength: 2147483647,
        minLength: 0,
        regEx: null,
        formType: "formField",
      },
      shippingAddress: {
        valid: true,
        htmlName: "dwfrm_shipping_shippingAddress",
        dynamicHtmlName: "dwfrm_shipping_shippingAddress_d0iyptbwfrqd",
        error: "address.invalid",
        attributes:
          'name = "dwfrm_shipping_shippingAddress" id = "dwfrm_shipping_shippingAddress"',
        formType: "formGroup",
        addressFields: {
          valid: true,
          htmlName: "dwfrm_shipping_shippingAddress_addressFields",
          dynamicHtmlName:
            "dwfrm_shipping_shippingAddress_addressFields_d0jwidwjknqi",
          error: null,
          attributes:
            'name = "dwfrm_shipping_shippingAddress_addressFields" id = "dwfrm_shipping_shippingAddress_addressFields"',
          formType: "formGroup",
          addressId: {
            htmlValue: "",
            mandatory: true,
            dynamicHtmlName:
              "dwfrm_shipping_shippingAddress_addressFields_addressId_d0hjigzynsze",
            htmlName: "dwfrm_shipping_shippingAddress_addressFields_addressId",
            valid: true,
            label: "Address Title",
            maxLength: 20,
            minLength: 0,
            regEx: null,
            formType: "formField",
          },
          firstName: {
            htmlValue: "",
            mandatory: true,
            dynamicHtmlName:
              "dwfrm_shipping_shippingAddress_addressFields_firstName_d0xtopblzfde",
            htmlName: "dwfrm_shipping_shippingAddress_addressFields_firstName",
            valid: true,
            label: "First Name",
            maxLength: 50,
            minLength: 0,
            regEx: null,
            formType: "formField",
          },
          lastName: {
            htmlValue: "",
            mandatory: true,
            dynamicHtmlName:
              "dwfrm_shipping_shippingAddress_addressFields_lastName_d0qjpcynuqtp",
            htmlName: "dwfrm_shipping_shippingAddress_addressFields_lastName",
            valid: true,
            label: "Last Name",
            maxLength: 50,
            minLength: 0,
            regEx: null,
            formType: "formField",
          },
          address1: {
            htmlValue: "",
            mandatory: true,
            dynamicHtmlName:
              "dwfrm_shipping_shippingAddress_addressFields_address1_d0ewgyjfvchk",
            htmlName: "dwfrm_shipping_shippingAddress_addressFields_address1",
            valid: true,
            label: "Address 1",
            maxLength: 50,
            minLength: 0,
            regEx: null,
            formType: "formField",
          },
          address2: {
            htmlValue: "",
            mandatory: "",
            dynamicHtmlName:
              "dwfrm_shipping_shippingAddress_addressFields_address2_d0ndgxjtbypl",
            htmlName: "dwfrm_shipping_shippingAddress_addressFields_address2",
            valid: true,
            label: "Address 2",
            maxLength: 50,
            minLength: 0,
            regEx: null,
            formType: "formField",
          },
          city: {
            htmlValue: "",
            mandatory: true,
            dynamicHtmlName:
              "dwfrm_shipping_shippingAddress_addressFields_city_d0ocamumdcod",
            htmlName: "dwfrm_shipping_shippingAddress_addressFields_city",
            valid: true,
            label: "City",
            maxLength: 50,
            minLength: 2,
            regEx: null,
            formType: "formField",
          },
          postalCode: {
            htmlValue: "",
            mandatory: true,
            dynamicHtmlName:
              "dwfrm_shipping_shippingAddress_addressFields_postalCode_d0wasqzmdwyj",
            htmlName: "dwfrm_shipping_shippingAddress_addressFields_postalCode",
            valid: true,
            label: "ZIP Code",
            maxLength: 10,
            minLength: 5,
            regEx:
              "(^\\d{5}(-\\d{4})?$)|(^[abceghjklmnprstvxyABCEGHJKLMNPRSTVXY]{1}\\d{1}[A-Za-z]{1} *\\d{1}[A-Za-z]{1}\\d{1}$)",
            formType: "formField",
          },
          country: {
            htmlValue: "",
            mandatory: true,
            dynamicHtmlName:
              "dwfrm_shipping_shippingAddress_addressFields_country_d0edwrxzigaw",
            htmlName: "dwfrm_shipping_shippingAddress_addressFields_country",
            valid: true,
            label: "Country",
            options: [
              {
                checked: false,
                htmlValue: "US",
                label: "United States",
                id: "US",
                selected: false,
                value: "US",
              },
            ],
            selectedOption: "",
            maxLength: 2147483647,
            minLength: 0,
            regEx: null,
            formType: "formField",
          },
          states: {
            valid: true,
            htmlName: "dwfrm_shipping_shippingAddress_addressFields_states",
            dynamicHtmlName:
              "dwfrm_shipping_shippingAddress_addressFields_states_d0sfnwrukukd",
            error: null,
            attributes:
              'name = "dwfrm_shipping_shippingAddress_addressFields_states" id = "dwfrm_shipping_shippingAddress_addressFields_states"',
            formType: "formGroup",
            stateCode: {
              htmlValue: "",
              mandatory: true,
              dynamicHtmlName:
                "dwfrm_shipping_shippingAddress_addressFields_states_stateCode_d0ikxiyzwsrx",
              htmlName:
                "dwfrm_shipping_shippingAddress_addressFields_states_stateCode",
              valid: true,
              label: "State",
              options: [
                {
                  checked: false,
                  htmlValue: "",
                  label: "",
                  id: "",
                  selected: false,
                  value: null,
                },
                {
                  checked: false,
                  htmlValue: "AL",
                  label: "Alabama",
                  id: "AL",
                  selected: false,
                  value: "AL",
                },
                {
                  checked: false,
                  htmlValue: "AK",
                  label: "Alaska",
                  id: "AK",
                  selected: false,
                  value: "AK",
                },
                {
                  checked: false,
                  htmlValue: "AS",
                  label: "American Samoa",
                  id: "AS",
                  selected: false,
                  value: "AS",
                },
                {
                  checked: false,
                  htmlValue: "AZ",
                  label: "Arizona",
                  id: "AZ",
                  selected: false,
                  value: "AZ",
                },
                {
                  checked: false,
                  htmlValue: "AR",
                  label: "Arkansas",
                  id: "AR",
                  selected: false,
                  value: "AR",
                },
                {
                  checked: false,
                  htmlValue: "CA",
                  label: "California",
                  id: "CA",
                  selected: false,
                  value: "CA",
                },
                {
                  checked: false,
                  htmlValue: "CO",
                  label: "Colorado",
                  id: "CO",
                  selected: false,
                  value: "CO",
                },
                {
                  checked: false,
                  htmlValue: "CT",
                  label: "Connecticut",
                  id: "CT",
                  selected: false,
                  value: "CT",
                },
                {
                  checked: false,
                  htmlValue: "DE",
                  label: "Delaware",
                  id: "DE",
                  selected: false,
                  value: "DE",
                },
                {
                  checked: false,
                  htmlValue: "DC",
                  label: "District of Columbia",
                  id: "DC",
                  selected: false,
                  value: "DC",
                },
                {
                  checked: false,
                  htmlValue: "FL",
                  label: "Florida",
                  id: "FL",
                  selected: false,
                  value: "FL",
                },
                {
                  checked: false,
                  htmlValue: "GA",
                  label: "Georgia",
                  id: "GA",
                  selected: false,
                  value: "GA",
                },
                {
                  checked: false,
                  htmlValue: "GU",
                  label: "Guam",
                  id: "GU",
                  selected: false,
                  value: "GU",
                },
                {
                  checked: false,
                  htmlValue: "HI",
                  label: "Hawaii",
                  id: "HI",
                  selected: false,
                  value: "HI",
                },
                {
                  checked: false,
                  htmlValue: "ID",
                  label: "Idaho",
                  id: "ID",
                  selected: false,
                  value: "ID",
                },
                {
                  checked: false,
                  htmlValue: "IL",
                  label: "Illinois",
                  id: "IL",
                  selected: false,
                  value: "IL",
                },
                {
                  checked: false,
                  htmlValue: "IN",
                  label: "Indiana",
                  id: "IN",
                  selected: false,
                  value: "IN",
                },
                {
                  checked: false,
                  htmlValue: "IA",
                  label: "Iowa",
                  id: "IA",
                  selected: false,
                  value: "IA",
                },
                {
                  checked: false,
                  htmlValue: "KS",
                  label: "Kansas",
                  id: "KS",
                  selected: false,
                  value: "KS",
                },
                {
                  checked: false,
                  htmlValue: "KY",
                  label: "Kentucky",
                  id: "KY",
                  selected: false,
                  value: "KY",
                },
                {
                  checked: false,
                  htmlValue: "LA",
                  label: "Louisiana",
                  id: "LA",
                  selected: false,
                  value: "LA",
                },
                {
                  checked: false,
                  htmlValue: "ME",
                  label: "Maine",
                  id: "ME",
                  selected: false,
                  value: "ME",
                },
                {
                  checked: false,
                  htmlValue: "MD",
                  label: "Maryland",
                  id: "MD",
                  selected: false,
                  value: "MD",
                },
                {
                  checked: false,
                  htmlValue: "MA",
                  label: "Massachusetts",
                  id: "MA",
                  selected: false,
                  value: "MA",
                },
                {
                  checked: false,
                  htmlValue: "MI",
                  label: "Michigan",
                  id: "MI",
                  selected: false,
                  value: "MI",
                },
                {
                  checked: false,
                  htmlValue: "MN",
                  label: "Minnesota",
                  id: "MN",
                  selected: false,
                  value: "MN",
                },
                {
                  checked: false,
                  htmlValue: "MS",
                  label: "Mississippi",
                  id: "MS",
                  selected: false,
                  value: "MS",
                },
                {
                  checked: false,
                  htmlValue: "MO",
                  label: "Missouri",
                  id: "MO",
                  selected: false,
                  value: "MO",
                },
                {
                  checked: false,
                  htmlValue: "MT",
                  label: "Montana",
                  id: "MT",
                  selected: false,
                  value: "MT",
                },
                {
                  checked: false,
                  htmlValue: "NE",
                  label: "Nebraska",
                  id: "NE",
                  selected: false,
                  value: "NE",
                },
                {
                  checked: false,
                  htmlValue: "NV",
                  label: "Nevada",
                  id: "NV",
                  selected: false,
                  value: "NV",
                },
                {
                  checked: false,
                  htmlValue: "NH",
                  label: "New Hampshire",
                  id: "NH",
                  selected: false,
                  value: "NH",
                },
                {
                  checked: false,
                  htmlValue: "NJ",
                  label: "New Jersey",
                  id: "NJ",
                  selected: false,
                  value: "NJ",
                },
                {
                  checked: false,
                  htmlValue: "NM",
                  label: "New Mexico",
                  id: "NM",
                  selected: false,
                  value: "NM",
                },
                {
                  checked: false,
                  htmlValue: "NY",
                  label: "New York",
                  id: "NY",
                  selected: false,
                  value: "NY",
                },
                {
                  checked: false,
                  htmlValue: "NC",
                  label: "North Carolina",
                  id: "NC",
                  selected: false,
                  value: "NC",
                },
                {
                  checked: false,
                  htmlValue: "ND",
                  label: "North Dakota",
                  id: "ND",
                  selected: false,
                  value: "ND",
                },
                {
                  checked: false,
                  htmlValue: "OH",
                  label: "Ohio",
                  id: "OH",
                  selected: false,
                  value: "OH",
                },
                {
                  checked: false,
                  htmlValue: "OK",
                  label: "Oklahoma",
                  id: "OK",
                  selected: false,
                  value: "OK",
                },
                {
                  checked: false,
                  htmlValue: "OR",
                  label: "Oregon",
                  id: "OR",
                  selected: false,
                  value: "OR",
                },
                {
                  checked: false,
                  htmlValue: "PA",
                  label: "Pennsylvania",
                  id: "PA",
                  selected: false,
                  value: "PA",
                },
                {
                  checked: false,
                  htmlValue: "PR",
                  label: "Puerto Rico",
                  id: "PR",
                  selected: false,
                  value: "PR",
                },
                {
                  checked: false,
                  htmlValue: "RI",
                  label: "Rhode Island",
                  id: "RI",
                  selected: false,
                  value: "RI",
                },
                {
                  checked: false,
                  htmlValue: "SC",
                  label: "South Carolina",
                  id: "SC",
                  selected: false,
                  value: "SC",
                },
                {
                  checked: false,
                  htmlValue: "SD",
                  label: "South Dakota",
                  id: "SD",
                  selected: false,
                  value: "SD",
                },
                {
                  checked: false,
                  htmlValue: "TN",
                  label: "Tennessee",
                  id: "TN",
                  selected: false,
                  value: "TN",
                },
                {
                  checked: false,
                  htmlValue: "TX",
                  label: "Texas",
                  id: "TX",
                  selected: false,
                  value: "TX",
                },
                {
                  checked: false,
                  htmlValue: "UT",
                  label: "Utah",
                  id: "UT",
                  selected: false,
                  value: "UT",
                },
                {
                  checked: false,
                  htmlValue: "VT",
                  label: "Vermont",
                  id: "VT",
                  selected: false,
                  value: "VT",
                },
                {
                  checked: false,
                  htmlValue: "VI",
                  label: "Virgin Islands",
                  id: "VI",
                  selected: false,
                  value: "VI",
                },
                {
                  checked: false,
                  htmlValue: "VA",
                  label: "Virginia",
                  id: "VA",
                  selected: false,
                  value: "VA",
                },
                {
                  checked: false,
                  htmlValue: "WA",
                  label: "Washington",
                  id: "WA",
                  selected: false,
                  value: "WA",
                },
                {
                  checked: false,
                  htmlValue: "WV",
                  label: "West Virginia",
                  id: "WV",
                  selected: false,
                  value: "WV",
                },
                {
                  checked: false,
                  htmlValue: "WI",
                  label: "Wisconsin",
                  id: "WI",
                  selected: false,
                  value: "WI",
                },
                {
                  checked: false,
                  htmlValue: "WY",
                  label: "Wyoming",
                  id: "WY",
                  selected: false,
                  value: "WY",
                },
                {
                  checked: false,
                  htmlValue: "AE",
                  label: "Armed Forces Africa",
                  id: "AE",
                  selected: false,
                  value: "AE",
                },
                {
                  checked: false,
                  htmlValue: "AA",
                  label: "Armed Forces America (exc. Canada)",
                  id: "AA",
                  selected: false,
                  value: "AA",
                },
                {
                  checked: false,
                  htmlValue: "AE",
                  label: "Armed Forces Canada",
                  id: "AE",
                  selected: false,
                  value: "AE",
                },
                {
                  checked: false,
                  htmlValue: "AE",
                  label: "Armed Forces Europe",
                  id: "AE",
                  selected: false,
                  value: "AE",
                },
                {
                  checked: false,
                  htmlValue: "AE",
                  label: "Armed Forces Middle East",
                  id: "AE",
                  selected: false,
                  value: "AE",
                },
                {
                  checked: false,
                  htmlValue: "AP",
                  label: "Armed Forces Pacific",
                  id: "AP",
                  selected: false,
                  value: "AP",
                },
                {
                  checked: false,
                  htmlValue: "OTHER",
                  label: "Non-US/Other",
                  id: "OTHER",
                  selected: false,
                  value: "OTHER",
                },
              ],
              selectedOption: "",
              maxLength: 2147483647,
              minLength: 0,
              regEx: null,
              formType: "formField",
            },
          },
          phone: {
            htmlValue: "",
            mandatory: true,
            dynamicHtmlName:
              "dwfrm_shipping_shippingAddress_addressFields_phone_d0omgebxhmom",
            htmlName: "dwfrm_shipping_shippingAddress_addressFields_phone",
            valid: true,
            description: "address.phone.example",
            label: "Phone Number",
            maxLength: 20,
            minLength: 10,
            regEx: null,
            formType: "formField",
          },
          apply: {
            description: null,
            label: null,
            submitted: false,
            triggered: false,
            formType: "formAction",
          },
          remove: {
            description: null,
            label: null,
            submitted: false,
            triggered: false,
            formType: "formAction",
          },
        },
        shippingMethodID: {
          htmlValue: "",
          mandatory: true,
          dynamicHtmlName:
            "dwfrm_shipping_shippingAddress_shippingMethodID_d0ioypvjnvfo",
          htmlName: "dwfrm_shipping_shippingAddress_shippingMethodID",
          valid: true,
          maxLength: 2147483647,
          minLength: 0,
          regEx: null,
          formType: "formField",
        },
        shippingAddressUseAsBillingAddress: {
          htmlValue: "true",
          mandatory: "",
          dynamicHtmlName:
            "dwfrm_shipping_shippingAddress_shippingAddressUseAsBillingAddress_d0ajsvbgjokn",
          htmlName:
            "dwfrm_shipping_shippingAddress_shippingAddressUseAsBillingAddress",
          valid: true,
          label: "checkout.shippingAddressUseAsBillingAddress",
          checked: false,
          selected: false,
          formType: "formField",
        },
        isGift: {
          htmlValue: "true",
          mandatory: "",
          dynamicHtmlName: "dwfrm_shipping_shippingAddress_isGift_d0echyhbktlf",
          htmlName: "dwfrm_shipping_shippingAddress_isGift",
          valid: true,
          label: "This is a gift.",
          checked: false,
          selected: false,
          formType: "formField",
        },
        giftMessage: {
          htmlValue: "",
          mandatory: "",
          dynamicHtmlName:
            "dwfrm_shipping_shippingAddress_giftMessage_d0wldrrprwev",
          htmlName: "dwfrm_shipping_shippingAddress_giftMessage",
          valid: true,
          label: "Message",
          maxLength: 250,
          minLength: 0,
          regEx: null,
          formType: "formField",
        },
        save: {
          description: null,
          label: null,
          submitted: false,
          triggered: false,
          formType: "formAction",
        },
      },
      base: {},
    },
    billingForm: {
      valid: true,
      htmlName: "dwfrm_billing",
      dynamicHtmlName: "dwfrm_billing_d0dyprmnupjt",
      error: null,
      attributes: 'name = "dwfrm_billing" id = "dwfrm_billing"',
      formType: "formGroup",
      shippingAddressUseAsBillingAddress: {
        htmlValue: "true",
        mandatory: "",
        dynamicHtmlName:
          "dwfrm_billing_shippingAddressUseAsBillingAddress_d0frojiiwdzg",
        htmlName: "dwfrm_billing_shippingAddressUseAsBillingAddress",
        valid: true,
        label: "profile.billingSameAsShipping",
        checked: false,
        selected: false,
        formType: "formField",
      },
      addressFields: {
        valid: true,
        htmlName: "dwfrm_billing_addressFields",
        dynamicHtmlName: "dwfrm_billing_addressFields_d0cxmzpioobq",
        error: null,
        attributes:
          'name = "dwfrm_billing_addressFields" id = "dwfrm_billing_addressFields"',
        formType: "formGroup",
        addressId: {
          htmlValue: "",
          mandatory: true,
          dynamicHtmlName: "dwfrm_billing_addressFields_addressId_d0uzuebloqfr",
          htmlName: "dwfrm_billing_addressFields_addressId",
          valid: true,
          label: "Address Title",
          maxLength: 20,
          minLength: 0,
          regEx: null,
          formType: "formField",
        },
        firstName: {
          htmlValue: "",
          mandatory: true,
          dynamicHtmlName: "dwfrm_billing_addressFields_firstName_d0mlwwyphglh",
          htmlName: "dwfrm_billing_addressFields_firstName",
          valid: true,
          label: "First Name",
          maxLength: 50,
          minLength: 0,
          regEx: null,
          formType: "formField",
        },
        lastName: {
          htmlValue: "",
          mandatory: true,
          dynamicHtmlName: "dwfrm_billing_addressFields_lastName_d0pfelzwuyti",
          htmlName: "dwfrm_billing_addressFields_lastName",
          valid: true,
          label: "Last Name",
          maxLength: 50,
          minLength: 0,
          regEx: null,
          formType: "formField",
        },
        address1: {
          htmlValue: "",
          mandatory: true,
          dynamicHtmlName: "dwfrm_billing_addressFields_address1_d0yxslslfyis",
          htmlName: "dwfrm_billing_addressFields_address1",
          valid: true,
          label: "Address 1",
          maxLength: 50,
          minLength: 0,
          regEx: null,
          formType: "formField",
        },
        address2: {
          htmlValue: "",
          mandatory: "",
          dynamicHtmlName: "dwfrm_billing_addressFields_address2_d0tdylisbruz",
          htmlName: "dwfrm_billing_addressFields_address2",
          valid: true,
          label: "Address 2",
          maxLength: 50,
          minLength: 0,
          regEx: null,
          formType: "formField",
        },
        city: {
          htmlValue: "",
          mandatory: true,
          dynamicHtmlName: "dwfrm_billing_addressFields_city_d0cfvnnrsuoz",
          htmlName: "dwfrm_billing_addressFields_city",
          valid: true,
          label: "City",
          maxLength: 50,
          minLength: 2,
          regEx: null,
          formType: "formField",
        },
        postalCode: {
          htmlValue: "",
          mandatory: true,
          dynamicHtmlName:
            "dwfrm_billing_addressFields_postalCode_d0qhdksorzjf",
          htmlName: "dwfrm_billing_addressFields_postalCode",
          valid: true,
          label: "ZIP Code",
          maxLength: 10,
          minLength: 5,
          regEx:
            "(^\\d{5}(-\\d{4})?$)|(^[abceghjklmnprstvxyABCEGHJKLMNPRSTVXY]{1}\\d{1}[A-Za-z]{1} *\\d{1}[A-Za-z]{1}\\d{1}$)",
          formType: "formField",
        },
        country: {
          htmlValue: "",
          mandatory: true,
          dynamicHtmlName: "dwfrm_billing_addressFields_country_d0yovhxnmswq",
          htmlName: "dwfrm_billing_addressFields_country",
          valid: true,
          label: "Country",
          options: [
            {
              checked: false,
              htmlValue: "US",
              label: "United States",
              id: "US",
              selected: false,
              value: "US",
            },
          ],
          selectedOption: "",
          maxLength: 2147483647,
          minLength: 0,
          regEx: null,
          formType: "formField",
        },
        states: {
          valid: true,
          htmlName: "dwfrm_billing_addressFields_states",
          dynamicHtmlName: "dwfrm_billing_addressFields_states_d0arlkhcmmpg",
          error: null,
          attributes:
            'name = "dwfrm_billing_addressFields_states" id = "dwfrm_billing_addressFields_states"',
          formType: "formGroup",
          stateCode: {
            htmlValue: "",
            mandatory: true,
            dynamicHtmlName:
              "dwfrm_billing_addressFields_states_stateCode_d0qhmcjtmofl",
            htmlName: "dwfrm_billing_addressFields_states_stateCode",
            valid: true,
            label: "State",
            options: [
              {
                checked: false,
                htmlValue: "",
                label: "",
                id: "",
                selected: false,
                value: null,
              },
              {
                checked: false,
                htmlValue: "AL",
                label: "Alabama",
                id: "AL",
                selected: false,
                value: "AL",
              },
              {
                checked: false,
                htmlValue: "AK",
                label: "Alaska",
                id: "AK",
                selected: false,
                value: "AK",
              },
              {
                checked: false,
                htmlValue: "AS",
                label: "American Samoa",
                id: "AS",
                selected: false,
                value: "AS",
              },
              {
                checked: false,
                htmlValue: "AZ",
                label: "Arizona",
                id: "AZ",
                selected: false,
                value: "AZ",
              },
              {
                checked: false,
                htmlValue: "AR",
                label: "Arkansas",
                id: "AR",
                selected: false,
                value: "AR",
              },
              {
                checked: false,
                htmlValue: "CA",
                label: "California",
                id: "CA",
                selected: false,
                value: "CA",
              },
              {
                checked: false,
                htmlValue: "CO",
                label: "Colorado",
                id: "CO",
                selected: false,
                value: "CO",
              },
              {
                checked: false,
                htmlValue: "CT",
                label: "Connecticut",
                id: "CT",
                selected: false,
                value: "CT",
              },
              {
                checked: false,
                htmlValue: "DE",
                label: "Delaware",
                id: "DE",
                selected: false,
                value: "DE",
              },
              {
                checked: false,
                htmlValue: "DC",
                label: "District of Columbia",
                id: "DC",
                selected: false,
                value: "DC",
              },
              {
                checked: false,
                htmlValue: "FL",
                label: "Florida",
                id: "FL",
                selected: false,
                value: "FL",
              },
              {
                checked: false,
                htmlValue: "GA",
                label: "Georgia",
                id: "GA",
                selected: false,
                value: "GA",
              },
              {
                checked: false,
                htmlValue: "GU",
                label: "Guam",
                id: "GU",
                selected: false,
                value: "GU",
              },
              {
                checked: false,
                htmlValue: "HI",
                label: "Hawaii",
                id: "HI",
                selected: false,
                value: "HI",
              },
              {
                checked: false,
                htmlValue: "ID",
                label: "Idaho",
                id: "ID",
                selected: false,
                value: "ID",
              },
              {
                checked: false,
                htmlValue: "IL",
                label: "Illinois",
                id: "IL",
                selected: false,
                value: "IL",
              },
              {
                checked: false,
                htmlValue: "IN",
                label: "Indiana",
                id: "IN",
                selected: false,
                value: "IN",
              },
              {
                checked: false,
                htmlValue: "IA",
                label: "Iowa",
                id: "IA",
                selected: false,
                value: "IA",
              },
              {
                checked: false,
                htmlValue: "KS",
                label: "Kansas",
                id: "KS",
                selected: false,
                value: "KS",
              },
              {
                checked: false,
                htmlValue: "KY",
                label: "Kentucky",
                id: "KY",
                selected: false,
                value: "KY",
              },
              {
                checked: false,
                htmlValue: "LA",
                label: "Louisiana",
                id: "LA",
                selected: false,
                value: "LA",
              },
              {
                checked: false,
                htmlValue: "ME",
                label: "Maine",
                id: "ME",
                selected: false,
                value: "ME",
              },
              {
                checked: false,
                htmlValue: "MD",
                label: "Maryland",
                id: "MD",
                selected: false,
                value: "MD",
              },
              {
                checked: false,
                htmlValue: "MA",
                label: "Massachusetts",
                id: "MA",
                selected: false,
                value: "MA",
              },
              {
                checked: false,
                htmlValue: "MI",
                label: "Michigan",
                id: "MI",
                selected: false,
                value: "MI",
              },
              {
                checked: false,
                htmlValue: "MN",
                label: "Minnesota",
                id: "MN",
                selected: false,
                value: "MN",
              },
              {
                checked: false,
                htmlValue: "MS",
                label: "Mississippi",
                id: "MS",
                selected: false,
                value: "MS",
              },
              {
                checked: false,
                htmlValue: "MO",
                label: "Missouri",
                id: "MO",
                selected: false,
                value: "MO",
              },
              {
                checked: false,
                htmlValue: "MT",
                label: "Montana",
                id: "MT",
                selected: false,
                value: "MT",
              },
              {
                checked: false,
                htmlValue: "NE",
                label: "Nebraska",
                id: "NE",
                selected: false,
                value: "NE",
              },
              {
                checked: false,
                htmlValue: "NV",
                label: "Nevada",
                id: "NV",
                selected: false,
                value: "NV",
              },
              {
                checked: false,
                htmlValue: "NH",
                label: "New Hampshire",
                id: "NH",
                selected: false,
                value: "NH",
              },
              {
                checked: false,
                htmlValue: "NJ",
                label: "New Jersey",
                id: "NJ",
                selected: false,
                value: "NJ",
              },
              {
                checked: false,
                htmlValue: "NM",
                label: "New Mexico",
                id: "NM",
                selected: false,
                value: "NM",
              },
              {
                checked: false,
                htmlValue: "NY",
                label: "New York",
                id: "NY",
                selected: false,
                value: "NY",
              },
              {
                checked: false,
                htmlValue: "NC",
                label: "North Carolina",
                id: "NC",
                selected: false,
                value: "NC",
              },
              {
                checked: false,
                htmlValue: "ND",
                label: "North Dakota",
                id: "ND",
                selected: false,
                value: "ND",
              },
              {
                checked: false,
                htmlValue: "OH",
                label: "Ohio",
                id: "OH",
                selected: false,
                value: "OH",
              },
              {
                checked: false,
                htmlValue: "OK",
                label: "Oklahoma",
                id: "OK",
                selected: false,
                value: "OK",
              },
              {
                checked: false,
                htmlValue: "OR",
                label: "Oregon",
                id: "OR",
                selected: false,
                value: "OR",
              },
              {
                checked: false,
                htmlValue: "PA",
                label: "Pennsylvania",
                id: "PA",
                selected: false,
                value: "PA",
              },
              {
                checked: false,
                htmlValue: "PR",
                label: "Puerto Rico",
                id: "PR",
                selected: false,
                value: "PR",
              },
              {
                checked: false,
                htmlValue: "RI",
                label: "Rhode Island",
                id: "RI",
                selected: false,
                value: "RI",
              },
              {
                checked: false,
                htmlValue: "SC",
                label: "South Carolina",
                id: "SC",
                selected: false,
                value: "SC",
              },
              {
                checked: false,
                htmlValue: "SD",
                label: "South Dakota",
                id: "SD",
                selected: false,
                value: "SD",
              },
              {
                checked: false,
                htmlValue: "TN",
                label: "Tennessee",
                id: "TN",
                selected: false,
                value: "TN",
              },
              {
                checked: false,
                htmlValue: "TX",
                label: "Texas",
                id: "TX",
                selected: false,
                value: "TX",
              },
              {
                checked: false,
                htmlValue: "UT",
                label: "Utah",
                id: "UT",
                selected: false,
                value: "UT",
              },
              {
                checked: false,
                htmlValue: "VT",
                label: "Vermont",
                id: "VT",
                selected: false,
                value: "VT",
              },
              {
                checked: false,
                htmlValue: "VI",
                label: "Virgin Islands",
                id: "VI",
                selected: false,
                value: "VI",
              },
              {
                checked: false,
                htmlValue: "VA",
                label: "Virginia",
                id: "VA",
                selected: false,
                value: "VA",
              },
              {
                checked: false,
                htmlValue: "WA",
                label: "Washington",
                id: "WA",
                selected: false,
                value: "WA",
              },
              {
                checked: false,
                htmlValue: "WV",
                label: "West Virginia",
                id: "WV",
                selected: false,
                value: "WV",
              },
              {
                checked: false,
                htmlValue: "WI",
                label: "Wisconsin",
                id: "WI",
                selected: false,
                value: "WI",
              },
              {
                checked: false,
                htmlValue: "WY",
                label: "Wyoming",
                id: "WY",
                selected: false,
                value: "WY",
              },
              {
                checked: false,
                htmlValue: "AE",
                label: "Armed Forces Africa",
                id: "AE",
                selected: false,
                value: "AE",
              },
              {
                checked: false,
                htmlValue: "AA",
                label: "Armed Forces America (exc. Canada)",
                id: "AA",
                selected: false,
                value: "AA",
              },
              {
                checked: false,
                htmlValue: "AE",
                label: "Armed Forces Canada",
                id: "AE",
                selected: false,
                value: "AE",
              },
              {
                checked: false,
                htmlValue: "AE",
                label: "Armed Forces Europe",
                id: "AE",
                selected: false,
                value: "AE",
              },
              {
                checked: false,
                htmlValue: "AE",
                label: "Armed Forces Middle East",
                id: "AE",
                selected: false,
                value: "AE",
              },
              {
                checked: false,
                htmlValue: "AP",
                label: "Armed Forces Pacific",
                id: "AP",
                selected: false,
                value: "AP",
              },
              {
                checked: false,
                htmlValue: "OTHER",
                label: "Non-US/Other",
                id: "OTHER",
                selected: false,
                value: "OTHER",
              },
            ],
            selectedOption: "",
            maxLength: 2147483647,
            minLength: 0,
            regEx: null,
            formType: "formField",
          },
        },
        phone: {
          htmlValue: "",
          mandatory: true,
          dynamicHtmlName: "dwfrm_billing_addressFields_phone_d0qryunosuub",
          htmlName: "dwfrm_billing_addressFields_phone",
          valid: true,
          description: "address.phone.example",
          label: "Phone Number",
          maxLength: 20,
          minLength: 10,
          regEx: null,
          formType: "formField",
        },
        apply: {
          description: null,
          label: null,
          submitted: false,
          triggered: false,
          formType: "formAction",
        },
        remove: {
          description: null,
          label: null,
          submitted: false,
          triggered: false,
          formType: "formAction",
        },
      },
      contactInfoFields: {
        valid: true,
        htmlName: "dwfrm_billing_contactInfoFields",
        dynamicHtmlName: "dwfrm_billing_contactInfoFields_d0zipnrpkpmd",
        error: null,
        attributes:
          'name = "dwfrm_billing_contactInfoFields" id = "dwfrm_billing_contactInfoFields"',
        formType: "formGroup",
        email: {
          htmlValue: "",
          mandatory: true,
          dynamicHtmlName: "dwfrm_billing_contactInfoFields_email_d0fhwodrbijg",
          htmlName: "dwfrm_billing_contactInfoFields_email",
          valid: true,
          label: "profile.email",
          maxLength: 50,
          minLength: 0,
          regEx: "^[\\w.%+-]+@[\\w.-]+\\.[\\w]{2,6}$",
          formType: "formField",
        },
        phone: {
          htmlValue: "",
          mandatory: true,
          dynamicHtmlName: "dwfrm_billing_contactInfoFields_phone_d0mpizxcsbxg",
          htmlName: "dwfrm_billing_contactInfoFields_phone",
          valid: true,
          description: "address.phone.example",
          label: "profile.phone",
          maxLength: 20,
          minLength: 10,
          regEx: null,
          formType: "formField",
        },
      },
      paymentMethod: {
        htmlValue: "",
        mandatory: true,
        dynamicHtmlName: "dwfrm_billing_paymentMethod_d0mwgultdjaa",
        htmlName: "dwfrm_billing_paymentMethod",
        valid: true,
        maxLength: 2147483647,
        minLength: 0,
        regEx: null,
        formType: "formField",
      },
      creditCardFields: {
        valid: true,
        htmlName: "dwfrm_billing_creditCardFields",
        dynamicHtmlName: "dwfrm_billing_creditCardFields_d0rkrkrdfsnc",
        error: null,
        attributes:
          'name = "dwfrm_billing_creditCardFields" id = "dwfrm_billing_creditCardFields"',
        formType: "formGroup",
        editNumber: {
          htmlValue: "",
          mandatory: "",
          dynamicHtmlName:
            "dwfrm_billing_creditCardFields_editNumber_d0sqktqvrefq",
          htmlName: "dwfrm_billing_creditCardFields_editNumber",
          valid: true,
          label: "Card Number",
          maxLength: 16,
          minLength: 0,
          regEx: null,
          formType: "formField",
        },
        paymentMethod: {
          htmlValue: "",
          mandatory: true,
          dynamicHtmlName:
            "dwfrm_billing_creditCardFields_paymentMethod_d0zscnqvbyec",
          htmlName: "dwfrm_billing_creditCardFields_paymentMethod",
          valid: true,
          maxLength: 2147483647,
          minLength: 0,
          regEx: null,
          formType: "formField",
        },
        cardType: {
          htmlValue: "",
          mandatory: true,
          dynamicHtmlName:
            "dwfrm_billing_creditCardFields_cardType_d0oeiitkrwtg",
          htmlName: "dwfrm_billing_creditCardFields_cardType",
          valid: true,
          label: "profile.cardtype",
          maxLength: 16,
          minLength: 0,
          regEx: null,
          formType: "formField",
        },
        cardNumber: {
          htmlValue: "",
          mandatory: true,
          dynamicHtmlName:
            "dwfrm_billing_creditCardFields_cardNumber_d0llvhzctknb",
          htmlName: "dwfrm_billing_creditCardFields_cardNumber",
          valid: true,
          label: "Card Number",
          maxLength: 20,
          minLength: 0,
          regEx: null,
          formType: "formField",
        },
        cardOwner: {
          htmlValue: "",
          mandatory: true,
          dynamicHtmlName:
            "dwfrm_billing_creditCardFields_cardOwner_d0jmzflniopu",
          htmlName: "dwfrm_billing_creditCardFields_cardOwner",
          valid: true,
          label: "Name on Card",
          maxLength: 16,
          minLength: 0,
          regEx: null,
          formType: "formField",
        },
        expirationMonth: {
          htmlValue: "",
          mandatory: true,
          dynamicHtmlName:
            "dwfrm_billing_creditCardFields_expirationMonth_d0ivexschsla",
          htmlName: "dwfrm_billing_creditCardFields_expirationMonth",
          valid: true,
          label: "Expiration Month",
          options: [
            {
              checked: false,
              htmlValue: "",
              label: "month",
              id: "",
              selected: false,
              value: null,
            },
            {
              checked: false,
              htmlValue: "1",
              label: "01",
              id: "01",
              selected: false,
              value: 1,
            },
            {
              checked: false,
              htmlValue: "2",
              label: "02",
              id: "02",
              selected: false,
              value: 2,
            },
            {
              checked: false,
              htmlValue: "3",
              label: "03",
              id: "03",
              selected: false,
              value: 3,
            },
            {
              checked: false,
              htmlValue: "4",
              label: "04",
              id: "04",
              selected: false,
              value: 4,
            },
            {
              checked: false,
              htmlValue: "5",
              label: "05",
              id: "05",
              selected: false,
              value: 5,
            },
            {
              checked: false,
              htmlValue: "6",
              label: "06",
              id: "06",
              selected: false,
              value: 6,
            },
            {
              checked: false,
              htmlValue: "7",
              label: "07",
              id: "07",
              selected: false,
              value: 7,
            },
            {
              checked: false,
              htmlValue: "8",
              label: "08",
              id: "08",
              selected: false,
              value: 8,
            },
            {
              checked: false,
              htmlValue: "9",
              label: "09",
              id: "09",
              selected: false,
              value: 9,
            },
            {
              checked: false,
              htmlValue: "10",
              label: "10",
              id: "10",
              selected: false,
              value: 10,
            },
            {
              checked: false,
              htmlValue: "11",
              label: "11",
              id: "11",
              selected: false,
              value: 11,
            },
            {
              checked: false,
              htmlValue: "12",
              label: "12",
              id: "12",
              selected: false,
              value: 12,
            },
          ],
          selectedOption: "",
          maxValue: null,
          minValue: null,
          formType: "formField",
        },
        expirationYear: {
          htmlValue: "",
          mandatory: true,
          dynamicHtmlName:
            "dwfrm_billing_creditCardFields_expirationYear_d0rsgnrljwsg",
          htmlName: "dwfrm_billing_creditCardFields_expirationYear",
          valid: true,
          label: "Expiration Year",
          options: [
            {
              checked: false,
              htmlValue: "",
              label: "year",
              id: "",
              selected: false,
              value: null,
            },
          ],
          selectedOption: "",
          maxValue: null,
          minValue: null,
          formType: "formField",
        },
        securityCode: {
          htmlValue: "",
          mandatory: true,
          dynamicHtmlName:
            "dwfrm_billing_creditCardFields_securityCode_d0yyltgasgws",
          htmlName: "dwfrm_billing_creditCardFields_securityCode",
          valid: true,
          label: "profile.securitycode",
          maxLength: 4,
          minLength: 0,
          regEx: null,
          formType: "formField",
        },
        saveCard: {
          htmlValue: "true",
          mandatory: "",
          dynamicHtmlName:
            "dwfrm_billing_creditCardFields_saveCard_d0okgybflwor",
          htmlName: "dwfrm_billing_creditCardFields_saveCard",
          valid: true,
          label: "Save Card to Account",
          checked: false,
          selected: false,
          formType: "formField",
        },
      },
      subscribe: {
        htmlValue: "true",
        mandatory: "",
        dynamicHtmlName: "dwfrm_billing_subscribe_d0xpmbtaecqa",
        htmlName: "dwfrm_billing_subscribe",
        valid: true,
        checked: false,
        selected: false,
        formType: "formField",
      },
      base: {},
    },
  },
  expirationYears: [2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029],
  currentStage: "shipping",
  reportingURLs: [{}],
};
export default checkoutMocked;
